---
title: "R Notebook"
output: html_notebook
---
Name:Swaroop Srisailam

```{r}
fav <- c(15,45,56,20,34)
result <- pie(fav,
              main = "Favorite fruit",
              lables <- c("apple","orange","mango","blue berry","guava"),
              col = c("red", "orange", "yellow", "blue", "green")
              )
print(result)
```
BAR Plot
```{r}
s <- c(9,11,3,20,0,5,12,5)
m <- c("game-1","game-2","game-3","game-4","game-5","game-6","game-7","game-8")

barplot(s,names.arg=m,xlab="Basketball ", ylab ="Score",col="yellow",
        main = "basketball league",border ='black')
```
Stacked BAR chart
```{r}
colors = c("green","black","white")
subjects <- c("101","102","103","104","105")
students <- c("Satya","Sai","Venkat")

Values <- matrix(c(2,9,3,11,9,4,8,7,3,12,5,2,8,10,11), nrow = 3, ncol = 5, byrow = TRUE)

barplot(Values, main = "Academic Performance Subject-Wise", names.arg = subjects, xlab = "Subjects", ylab = "Marks-Secured", col = colors)

legend("topleft",regions=TRUE, cex = 1.3, fill = colors)
```
Box PLOT
```{r}
inp<- mtcars[,c('mpg','cyl')]
print(head(inp))

boxplot(mpg ~ cyl, data = mtcars, xlab = "Number of Cylinders",
   ylab = "Miles Per Gallon", main = "Mileage Data")

```
Histogram
```{r}
x<-c(1,55,36,98,7,67,86,10)

hist(x,xlab = "Weight",col = "skyblue",border = "black")
```
Line Plot
```{r}
v <- c(10,22,2,4,3,6,8)

plot(v,type = "o", col = "black", xlab = "# of games", ylab = "baskets",
   main = "Basketball Performance")
```
Multile Lines in a Chart:

```{r}
sathyaHouse<- c(10,8,4,3,2)
DharmaHouse <- c(2,7,10,9,3)

plot(sathyaHouse,type = "o", col = "blue", xlab = "Matches", ylab = "Baskets",
   main = "Basketball House Match")

lines(DharmaHouse, type = "o", col = "red")
```


SCATTER PLOT:

```{r}
input <- mtcars[,c('wt','mpg')]

plot(x = input$wt,y = input$mpg,
   xlab = "Weight",
   ylab = "Milage",
   xlim = c(1.5,4),
   ylim = c(15,40),		 
   main = "Weight vs Milage"
)


```


```{r}
pairs(~wt+mpg+disp+cyl,data = mtcars,
   main = "Scatterplot Matrix")
```

MEASURES OF CENTRAL TENDENCY (MEAN, MEDIAN , MODE):

```{r}
x <- c(2,3,77,645,43,23,-55,43,22)

mean <-mean(x)
paste("MEAN : ",mean)

```


```{r}
x <- c(3,5,3,2,4.5,NA,9.1,32,24,NA,NA,18,NA,NA)
mean <-  mean(x,na.rm = TRUE)
paste("MEAN after dropping NA values :",mean)

```

MEDIAN:

```{r}
median <- median(x)
paste("Median :",median)
```

```{r}
x <- c(3,5,3,2,4.5,NA,9.1,32,24,NA,NA,18,NA,NA)
median <-  median(x,na.rm = TRUE)
paste("MEDIAN after dropping NA values :",median)
```

MODE:

```{r}
Mode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}


x <- c(2,3,77,645,43,23,-55,43,22)
mode <- Mode(x)
paste("MODE of the given vector is :",mode)
```
Finding Mean,Median & Mode  for a  DATASET:

```{r}
D <- mtcars

mean(D$wt)
```

```{r}
median(D$wt)
```

```{r}
names(sort(-table(D$wt)))[1]
```


```{r}
quantile(D$wt, c(0.75))
```

