---
title: "Tidyverse(Swaroop Srisailam)"
output: html_notebook
---

```{r}
library(nycflights13)
library(tidyverse)
```

```{r}
flights
```

## 
dplyr Basics

```{r}
june23<-filter(flights, month == 6, day == 23)
june23
```

## Comparison

```{r}
filter(flights, arr_delay <= 110, dep_delay <= 130)
```

## Arrange

```{r}
arrange(flights, year, month, day)
```

```{r}
arrange(flights, desc(arr_delay))
```

## Select

```{r}
select(flights, year, month, day)
```

```{r}
select(flights, time_hour, air_time, everything())
```

## Adding new Variable 

```{r}
flights_sml <- select(flights,year:day,ends_with("delay"),distance,air_time)

mutate(flights_sml,gain = arr_delay - dep_delay,speed = distance / air_time* 60)

```

## Grouped Summaries

```{r}
summarize(flights, delay = mean(dep_delay, na.rm = TRUE))
```

```{r}
by_day <- group_by(flights, year, month, day)
summarize(by_day, delay = mean(dep_delay, na.rm = TRUE))
```

## Combining Multiple Operations with the Pipe

```{r}
by_dest <- group_by(flights, dest)
delay <- summarize(by_dest,count = n(),dist = mean(distance, na.rm = TRUE),
 delay = mean(arr_delay, na.rm = TRUE)
)
delay <- filter(delay, count > 20, dest != "HNL")

ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
 geom_point(aes(size = count), alpha = 1/3) +
 geom_smooth(se = FALSE)

```

## Missing Values 


```{r}
not_cancelled <- flights %>%
 filter(!is.na(dep_delay), !is.na(arr_delay))
not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(mean = mean(dep_delay))

```

## Counts

```{r}
delays <- not_cancelled %>%
 group_by(tailnum) %>%
 summarize(
 delay = mean(arr_delay)
 )
ggplot(data = delays, mapping = aes(x = delay)) +
 geom_freqpoly(binwidth = 10)
```


